// Mocks generated by Mockito 5.4.4 from annotations
// in yummy/test/data/repositories/db_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drift/drift.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:yummy/data/database/book_db.dart' as _i2;
import 'package:yummy/data/models/models.dart' as _i5;

// clang-format off

/// A class which mocks [BookDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookDatabase extends _i1.Mock implements _i2.BookDatabase {
  @override
  _i2.BookDao get bookDao => (super.noSuchMethod(
        Invocation.getter(#bookDao),
        returnValue: _FakeBookDao_0(
          this,
          Invocation.getter(#bookDao),
        ),
        returnValueForMissingStub: _FakeBookDao_0(
          this,
          Invocation.getter(#bookDao),
        ),
      ) as _i2.BookDao);

  @override
  _i2.BookTagDao get bookTagDao => (super.noSuchMethod(
        Invocation.getter(#bookTagDao),
        returnValue: _FakeBookTagDao_1(
          this,
          Invocation.getter(#bookTagDao),
        ),
        returnValueForMissingStub: _FakeBookTagDao_1(
          this,
          Invocation.getter(#bookTagDao),
        ),
      ) as _i2.BookTagDao);

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [BookDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookDao extends _i1.Mock implements _i2.BookDao {
  @override
  _i3.Future<List<_i2.DbBookData>> findAllBooks() => (super.noSuchMethod(
        Invocation.method(#findAllBooks, []),
        returnValue:
            _i3.Future<List<_i2.DbBookData>>.value(<_i2.DbBookData>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.DbBookData>>.value(<_i2.DbBookData>[]),
      ) as _i3.Future<List<_i2.DbBookData>>);

  @override
  _i3.Stream<List<_i5.Book>> watchAllBooks() => (super.noSuchMethod(
        Invocation.method(#watchAllBooks, []),
        returnValue: _i3.Stream<List<_i5.Book>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i5.Book>>.empty(),
      ) as _i3.Stream<List<_i5.Book>>);

  @override
  _i3.Future<List<_i2.DbBookData>> findBookById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#findBookById, [id]),
        returnValue:
            _i3.Future<List<_i2.DbBookData>>.value(<_i2.DbBookData>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.DbBookData>>.value(<_i2.DbBookData>[]),
      ) as _i3.Future<List<_i2.DbBookData>>);

  @override
  _i3.Future<int> insertBook(_i4.Insertable<_i2.DbBookData>? book) =>
      (super.noSuchMethod(
        Invocation.method(#insertBook, [book]),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<dynamic> deleteBook(int? id) => (super.noSuchMethod(
        Invocation.method(#deleteBook, [id]),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}

/// A class which mocks [BookTagDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookTagDao extends _i1.Mock implements _i2.BookTagDao {
  @override
  _i3.Future<List<_i2.DbBookTagData>> findAllTags() => (super.noSuchMethod(
        Invocation.method(#findAllTags, []),
        returnValue:
            _i3.Future<List<_i2.DbBookTagData>>.value(<_i2.DbBookTagData>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.DbBookTagData>>.value(<_i2.DbBookTagData>[]),
      ) as _i3.Future<List<_i2.DbBookTagData>>);

  @override
  _i3.Stream<List<_i2.DbBookTagData>> watchAllTags() => (super.noSuchMethod(
        Invocation.method(#watchAllTags, []),
        returnValue: _i3.Stream<List<_i2.DbBookTagData>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i2.DbBookTagData>>.empty(),
      ) as _i3.Stream<List<_i2.DbBookTagData>>);

  @override
  _i3.Future<List<_i2.DbBookTagData>> findBookTags(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#findBookTags, [id]),
        returnValue:
            _i3.Future<List<_i2.DbBookTagData>>.value(<_i2.DbBookTagData>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.DbBookTagData>>.value(<_i2.DbBookTagData>[]),
      ) as _i3.Future<List<_i2.DbBookTagData>>);

  @override
  _i3.Future<int> insertTag(_i4.Insertable<_i2.DbBookTagData>? tag) =>
      (super.noSuchMethod(
        Invocation.method(#insertTag, [tag]),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<dynamic> deleteTag(int? id) => (super.noSuchMethod(
        Invocation.method(#deleteTag, [id]),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}

class _FakeBookDao_0 extends _i1.SmartFake implements _i2.BookDao {
  _FakeBookDao_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeBookTagDao_1 extends _i1.SmartFake implements _i2.BookTagDao {
  _FakeBookTagDao_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}
