platform :osx, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

def patch_grpc_template_keyword
  %w[
    Pods/gRPC-Core/src/core/lib/promise/detail/basic_seq.h
    Pods/gRPC-C++/src/core/lib/promise/detail/basic_seq.h
  ].each do |relative_path|
    path = File.expand_path(relative_path, __dir__)
    next unless File.exist?(path)

    text = File.read(path)
    patched = text.gsub('Traits::template CallSeqFactory', 'Traits::CallSeqFactory')
    next if patched == text

    File.chmod(0o644, path)
    File.write(path, patched)
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'

      %w[OTHER_CFLAGS OTHER_CPLUSPLUSFLAGS GCC_PREPROCESSOR_DEFINITIONS].each do |key|
        if config.build_settings[key].is_a?(String)
          config.build_settings[key] = config.build_settings[key].gsub('-G', '')
        elsif config.build_settings[key].is_a?(Array)
          config.build_settings[key].delete('-G')
        end
      end
    end

    next unless target.respond_to?(:source_build_phase) && target.source_build_phase

    target.source_build_phase.files.each do |file|
      next unless file.settings && file.settings['COMPILER_FLAGS']

      flags = file.settings['COMPILER_FLAGS'].split
      flags.delete('-GCC_WARN_INHIBIT_ALL_WARNINGS')
      file.settings['COMPILER_FLAGS'] = flags.join(' ')
    end
  end

  patch_grpc_template_keyword
end
